name: Build ESP32 Sketch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Arduino CLI
      uses: arduino/setup-arduino-cli@v1.1.2  # ✅ sửa lỗi ở đây

    - name: Install ESP32 core
      run: |
        arduino-cli core update-index
        arduino-cli core install esp32:esp32

    - name: Compile sketch
      run: arduino-cli compile --fqbn esp32:esp32:esp32 src/

    - name: Upload compiled binary
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: src/build/*.bin
